apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: commandes
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: commandes
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75