apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  instances: 1
  bootstrap:
    initdb:
      database: markets
      owner: markets
      secret:
        name: cnpg-secret
  storage:
    size: 5Gi
    storageClass: cephfs
  postgresql:
    parameters:
      max_connections: "200"
      superuser_reserved_connections: "5"
      statement_timeout: "30000"
      idle_in_transaction_session_timeout: "30000"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: markets-pooler-rw
spec:
  cluster:
    name: cnpg
  type: rw
  instances: 1
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "2000"
      default_pool_size: "10"
      min_pool_size: "0"
      reserve_pool_size: "5"
      max_db_connections: "120"
      query_wait_timeout: "5000"
      server_idle_timeout: "300"  
      ignore_startup_parameters: "extra_float_digits,options"
