apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: wordpress-secret-sync
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: admin_password
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-admin-password
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: db_password
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-db-password
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: db_root_password
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-db-root-password
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: auth_key
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-auth-key
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: secure_auth_key
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-secure-auth-key
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: logged_in_key
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-logged-in-key
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: nonce_key
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-nonce-key
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: auth_salt
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-auth-salt
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: secure_auth_salt
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-secure-auth-salt
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: logged_in_salt
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-logged-in-salt
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: nonce_salt
      path: kv/data/wordpress-smoke-test-wordpress/default/wordpress/wordpress-nonce-salt
  output:
    name: wordpress-secret
    stringData:
      WORDPRESS_ADMIN_PASSWORD: "{{ .admin_password.password }}"
      MYSQL_PASSWORD: "{{ .db_password.password }}"
      MYSQL_ROOT_PASSWORD: "{{ .db_root_password.password }}"
      WORDPRESS_DB_PASSWORD: "{{ .db_password.password }}"
      WORDPRESS_AUTH_KEY: "{{ .auth_key.password }}"
      WORDPRESS_SECURE_AUTH_KEY: "{{ .secure_auth_key.password }}"
      WORDPRESS_LOGGED_IN_KEY: "{{ .logged_in_key.password }}"
      WORDPRESS_NONCE_KEY: "{{ .nonce_key.password }}"
      WORDPRESS_AUTH_SALT: "{{ .auth_salt.password }}"
      WORDPRESS_SECURE_AUTH_SALT: "{{ .secure_auth_salt.password }}"
      WORDPRESS_LOGGED_IN_SALT: "{{ .logged_in_salt.password }}"
      WORDPRESS_NONCE_SALT: "{{ .nonce_salt.password }}"
    type: Opaque
