apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrale-website
  annotations:
    kube-score/ignore: container-image-pull-policy,container-image-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrale-website
  template:
    metadata:
      labels:
        app: integrale-website
    spec:
      containers:
        - name: integrale-website
          image: ghcr.io/integrale-ets/site-integrale:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: yarn-tmp
              mountPath: /tmp
            - name: yarn-global
              mountPath: /usr/local/share/.cache/yarn
      volumes:
        - name: yarn-tmp
          emptyDir: {}
        - name: yarn-global
          emptyDir: {}
