apiVersion: apps/v1
kind: Deployment
metadata:
  name: markets-frontend
spec:
  selector:
    matchLabels:
      app: markets-frontend
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/algoets/markets-frontend:dernier