apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: markets-salt
spec:
  authentication:
    path: kubernetes
    role: secret-writer
    serviceAccount:
      name: default
  isKVSecretsEngineV2: true
  path: kv/data/markets-dev/default
  secretKey: SALT_SECRET_KEY
  secretFormat:
    passwordPolicyName: password-policy
