apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: markets-env-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: salt
      path: kv/data/markets-dev/default/markets-salt
  output:
    name: markets-env-secret
    stringData:
      SALT_SECRET_KEY: '{{ .salt.SALT_SECRET_KEY }}'
    type: opaque
