apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  instances: 1
  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - wiki
        source:
          externalCluster: wiki-pg
  storage:
    size: 10Gi
  postgresql:
    parameters:
      max_connections: "200"
      superuser_reserved_connections: "5"
      statement_timeout: "30000"
      idle_in_transaction_session_timeout: "30000"

  externalClusters:
    - name: wiki-pg
      connectionParameters:
        host: 10.109.13.252
        user: postgres
        dbname: wiki
      password:
        name: wikijs-postgres-secret
        key: postgresql-password
