apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-cedille
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: wiki=ghcr.io/clubcedille/wiki-cedille:latest
    argocd-image-updater.argoproj.io/wiki.update-strategy: digest
spec:
  project: default
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production
    namespace: wiki-cedille
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production
    path: apps/wiki-cedille/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
