apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: planifets-chatbot-qdrant
  annotations:
    kube-score/ignore: pod-networkpolicy, pod-probes
spec:
  serviceName: planifets-chatbot-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: planifets-chatbot-qdrant
  template:
    metadata:
      labels:
        app: planifets-chatbot-qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
          env:
            - name: QDRANT__SERVICE__API_KEY
              valueFrom:
                secretKeyRef:
                  name: planifets-chatbot-secret
                  key: qdrant_api_key
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 800m
              memory: 1Gi
              ephemeral-storage: 1Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cephfs
        resources:
          requests:
            storage: 5Gi
