apiVersion: v1
kind: Service
metadata:
  name: synapsets-service
spec:
  ports:
    - name: http
      targetPort: 80
      protocol: TCP
      port: 80
  type: ClusterIP
  selector:
    app: synapsets-web
