apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: wiki
    releaseName: wiki
    version: 2.2.17
    repo: https://charts.js.wiki
    valuesInline:
      image.tag: 2.5
      imagePullPolicy: Always
      resources.limits:
        cpu: 400m
        memory: 512Mi
        ephemeral-storage: 1Gi
      resources.requests:
        cpu: 200m
        memory: 256Mi
      ingress.enabled: false
      postgresql:
        enabled: true
        image:
          registry: public.ecr.aws
          repository: bitnami/postgresql
          tag: 11.21.0-debian-11-r52
        existingSecret: wikijs-postgres-secret
        persistence:
          enabled: true
          size: 10Gi
          storageClass: cephfs
      startupProbe:
        initialDelaySeconds: 120
