apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: wiki
    releaseName: wiki
    version: 2.2.17
    repo: https://charts.js.wiki
    valuesInline:
      image.tag: 2.5
      imagePullPolicy: Always
      resources.limits:
        cpu: 400m
        memory: 512Mi
        ephemeral-storage: 1Gi
      resources.requests:
        cpu: 200m
        memory: 256Mi
      ingress.enabled: false
      readinessProbe:
        httpGet:
          path: /
          port: http
      postgresql:
        enabled: true
        image:
          registry: public.ecr.aws
          repository: bitnami/postgresql
          tag: 11.21.0-debian-11-r52
        existingSecret: wikijs-postgres-secret
        securityContext:
          enabled: false
        volumePermissions:
          enabled: false
        persistence:
          enabled: true
          size: 10Gi
          storageClass: cephfs
      startupProbe:
        initialDelaySeconds: 120
patches:
  - target:
      kind: Pod
      name: wiki-test-connection
    patch: |-
      - op: add
        path: /spec/containers/0/readinessProbe
        value:
          exec:
            command:
              - sh
              - -c
              - wget -q --spider wiki:80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
