apiVersion: apps/v1
kind: Deployment
metadata:
  name: saveursdegenie-service
  annotations:
    kube-score/ignore: pod-networkpolicy,container-image-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saveursdegenie-service
  template:
    metadata:
      labels:
        app: saveursdegenie-service
    spec:
      containers:
        - name: saveursdegenie-web
          image: clubcedille/saveursdegenie.etsmtl.ca
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: 256Mi
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
