apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
  name: aeroets-grav
spec:
  authentication:
    path: kubernetes
    role: config-admin
  path: github
  repositories:
    - aeroets.etsmtl.ca
  organizationName: ClubCedille
