apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
  name: comets-grav
spec:
  authentication:
    path: kubernetes
    role: config-admin
  path: github
  repositories:
    - comets.etsmtl.ca
  organizationName: ClubCedille
