apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planifets-chatbot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-cedille-production-v2
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2
    namespace: planifets-chatbot
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production-v2
    path: apps/applets/planifets-chatbot/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planifets-chatbot-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-cedille-production-v2
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2
    namespace: planifets-chatbot-staging
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production-v2
    path: apps/applets/planifets-chatbot/staging
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planifets-chatbot-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-cedille-production-v2
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2
    namespace: planifets-chatbot-dev
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production-v2
    path: apps/applets/planifets-chatbot/dev
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
