apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twentycrm-server-pvc
spec:
  storageClassName: cephfs
  volumeName: twentycrm-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
