apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raconteurs-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: ClubCedille
        repo: raconteurs.etsmtl.ca
        tokenRef:
          secretName: github-pr-token
          key: token
      requeueAfterSeconds: 90
  template:
    metadata:
      name: 'raconteurs-pr-{{.number}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      labels:
        app-type: "preview"
        preview-pr-number: "{{.number}}"
        preview-pr-branch: "{{.branch}}"
        preview-pr-sha: "{{.head_sha}}"
        source-owner: "ClubCedille"
        source-repo: "raconteurs.etsmtl.ca"
        preview-host: "pr-{{ .number }}.raconteurs.prodv2.cedille.club"
    spec:
      project: k8s-cedille-production-v2
      source:
        repoURL: https://github.com/ClubCedille/k8s-cedille-production-v2
        targetRevision: HEAD
        path: apps/raconteurs/preview
        kustomize:
          images:
            - 'ghcr.io/clubcedille/raconteurs.etsmtl.ca:{{.head_sha}}'
          nameSuffix: '-pr-{{.number}}'
          patches:
            - target:
                kind: HTTPProxy
                name: raconteurs-preview
              patch: |-
                - op: replace
                  path: /spec/virtualhost/fqdn
                  value: pr-{{.number}}.raconteurs.prodv2.cedille.club
            - target:
                kind: Certificate
                name: raconteurs-preview-tls
              patch: |-
                - op: replace
                  path: /spec/commonName
                  value: pr-{{.number}}.raconteurs.prodv2.cedille.club
                - op: replace
                  path: /spec/dnsNames/0
                  value: pr-{{.number}}.raconteurs.prodv2.cedille.club
            - target:
                group: projectcontour.io
                version: v1
                kind: HTTPProxy
                name: raconteurs-preview
              patch: |-
                - op: replace
                  path: /spec/routes/0/services/0/name
                  value: raconteurs-service-pr-{{.number}}
      destination:
        server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2
        namespace: 'raconteurs-pr-{{.number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
