---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  annotations:
    kube-score/ignore: pod-networkpolicy
spec:
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: 256Mi
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: 1Gi
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "trema"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trema-env-secret
                  key: mongo_password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
