apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingenieuses
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: webapp=ghcr.io/les-ingenieuses-de-l-ets/web-ingenieuses:latest
    argocd-image-updater.argoproj.io/webapp.update-strategy: digest
    argocd-image-updater.argoproj.io/webapp.pull-secret: pullsecret:argocd/ghcr-ingenieuses-secret
spec:
  project: k8s-cedille-production-v2
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2
    namespace: ingenieuses
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production-v2
    path: apps/ingenieuses/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
