apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: planifets-frontend-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: frontend
      path: kv/data/planifets-staging/default/planifets-staging/frontend
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: backend
      path: kv/data/planifets-staging/default/planifets-staging/backend
  output:
    name: planifets-frontend-secret
    stringData:
      umami_website_id: '{{ .frontend.umami_website_id }}'
      posthog_project_token: '{{ .backend.posthog_project_token }}'
    type: opaque
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: planifets-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: backend
      path: kv/data/planifets-staging/default/planifets-staging/backend
  output:
    name: planifets-secret
    stringData:
      db_url: '{{ .backend.db_url }}'
      posthog_api_key: '{{ .backend.posthog_api_key }}'
    type: opaque
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: cnpg-vault-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: db
      path: kv/data/planifets-staging/default/planifets-staging/cnpg
  output:
    name: cnpg-secret
    stringData:
      username: '{{ .db.username }}'
      password: '{{ .db.password }}'
    type: kubernetes.io/basic-auth
