apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preci
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production
    namespace: preci
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production
    path: apps/preci/wordpress/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
