apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: n8n
  namespace: n8n
resources:
  - postgres-configmap.yaml
  - postgres-deployment.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - n8n-service.yaml
  - n8n-deployment.yaml
  - pvc.yaml