apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-crabe
  annotations:
    kube-score/ignore: container-image-tag, pod-networkpolicy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-crabe
  template:
    metadata:
      labels:
        app: webapp-crabe
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: webapp-crabe
          env:
            - name: DB_DRIVER
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DB_DRIVER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DB_PASSWORD
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: DB_ROOT_PASSWORD
            - name: SITE_NAME
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: SITE_NAME
            - name: ITEMS_PER_PAGE_CONSOLE
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: ITEMS_PER_PAGE_CONSOLE
            - name: ITEMS_INVENTORY_PAGE
              valueFrom:
                secretKeyRef:
                  name: webapp-crabe-secrets
                  key: ITEMS_INVENTORY_PAGE
            - name: EMAIL_ADDRESS
              value: "crabe@ens.etsmtl.ca"
            - name: VERSION_NUMBER
              value: "1.0.2"
          image: ghcr.io/crabe-etsmtl/crabe-atelier:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
