apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twenty
resources:
  - resources/ingress.yaml
  - base/postgres.yaml
helmCharts:
  - name: twenty-crm
    version: 0.1.0
    repo: oci://ghcr.io/cloud-exit/charts/
    releaseName: twenty
    valuesFile: "helm/values.yaml"
