apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twenty
  namespace: argocd
spec:
  project: default
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production
    namespace: twenty
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production
    path: apps/twenty
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
