apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plane
resources:
  - resources/ingress.yaml
helmCharts:
  - name: plane-ce
    version: 1.3.1
    repo: https://helm.plane.so
    releaseName: plane
    valuesFile: "helm/values.yaml"
