apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-admin-password
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-db-password
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-db-root-password
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-auth-key
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-secure-auth-key
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-logged-in-key
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-nonce-key
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-auth-salt
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-secure-auth-salt
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-logged-in-salt
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: wordpress-nonce-salt
spec:
  authentication:
    path: kubernetes
    role: secret-writer
  isKVSecretsEngineV2: true
  path: wordpress
  secretKey: password
  secretFormat:
    passwordPolicyName: password-policy
