apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hi-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: k8s-cedille-production-v2
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production-v2
    targetRevision: HEAD
    path: apps/hi-events
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production-v2
    namespace: hi-events
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
