apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - base/configmap.yml
  - base/postgres-pvc.yml
  - base/postgres.yml
  - base/postgres-service.yml
  - base/redis.yml
  - base/hi-events-deployment.yml
  - base/hi-events-service.yml
  - base/network-policies.yml
  - base/ingress.yml
