apiVersion: v1
kind: ConfigMap
metadata:
  name: hi-events-config
  namespace: hi-events
data:
  # URLs runtime (les VITE_* sont baked au build dans l'image all-in-one, inutiles ici)
  APP_FRONTEND_URL: "https://hi-events.prodv2.cedille.club"
  APP_URL: "https://hi-events.prodv2.cedille.club"
  APP_DISABLE_REGISTRATION: "false"
  LOG_CHANNEL: "stderr"
  CORS_ALLOWED_ORIGINS: "https://hi-events.prodv2.cedille.club"

  FILESYSTEM_PUBLIC_DISK: "public"
  FILESYSTEM_PRIVATE_DISK: "local"

  DB_CONNECTION: "pgsql"
  DB_HOST: "hi-events-postgres"
  DB_PORT: "5432"
  DB_DATABASE: "hi_events"
  DB_USERNAME: "hi_events"

  REDIS_HOST: "hi-events-redis"
  REDIS_PORT: "6379"

  QUEUE_CONNECTION: "redis"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.example.com" # TODO: remplacer par le serveur SMTP dès qu'on en a un
  MAIL_PORT: "587"
  MAIL_FROM_ADDRESS: "noreply@cedille.club"
  MAIL_FROM_NAME: "Cedille Events"
