apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: cnpg-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: db
      path: kv/data/hi-events/default/db
  output:
    name: cnpg-secret
    stringData:
      username: '{{ .db.username }}'
      password: '{{ .db.password }}'
    type: kubernetes.io/basic-auth
    labels:
      app: hi-events
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: hi-events-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: app
      path: kv/data/hi-events/default/app
  output:
    name: hi-events-secret
    stringData:
      APP_KEY: '{{ .app.app_key }}'
      JWT_SECRET: '{{ .app.jwt_secret }}'
      MAIL_PASSWORD: '{{ .app.mail_password }}'
    type: Opaque
    labels:
      app: hi-events
