apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: planifets-frontend-secret
spec:
  refreshPeriod: 1h
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: secret-reader
        serviceAccount:
          name: default
      name: frontend
      path: kv/data/planifets/default/planifets/planifets-frontend
  output:
    name: planifets-frontend-secret
    stringData:
      umami_website_id: '{{ .frontend.umami_website_id }}'
      posthog_project_token: '{{ .frontend.posthog_project_token }}'
    type: opaque
